body:
  - attributes:
      description: 'Beschreibe in kurzen Sätzen wer, was tun möchte. Versuche dabei
        technische Implementierungsdetails zu vermeiden, und die User Story in einer
        Sprache zu erstellen, die der Kunde versteht.'
      label: 'Was möchte wer tun?'
      placeholder: Als XY möchte ich ZY tun...
    type: textarea
    validations:
      required: true
  - attributes:
      description: 'Beschreibe die Motivation hinter der User Story. Dies macht es
        bei der Implementierung leichter, gute Designentscheidungen zu treffen.'
      label: 'Warum möchte man es tun?'
      placeholder: Ich möchte ZY tun um WY zu erreichen...
      validations:
        required: true
    type: textarea
  - attributes:
    description: 'Wenn möglich, füge Screenshots oder passend SVGs hinzu. Gibt es
      die gewünschte Funktionalität bereits an anderer Stelle, verlinke die Ressourcen
      gerne hier.'
    label: Zusätzlicher Kontext
    placeholder: Eine ähnliche Funktionalität gibt es hier... Ein SVG bei dem es nicht
      funktioniert ist dieses...
    type: textarea
  - attributes:
    type: markdown
    value: 'Vielen Dank für das Erstellen der Nutzerstory. Falls du ein Entwickler
      bist, denke bitte daran alle nötigen Labels zu vergeben und die User Story beim
      nächsten Treffen zu schätzen!'
description: Erstelle eine neue User Story für unser Projekt
labels: User Story
name: User Story
title: "[User Story]"
